// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     ConnectResponse.avsc
 */

package schema

import (
	"github.com/actgardner/gogen-avro/compiler"
	"github.com/actgardner/gogen-avro/container"
	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
	"io"
)

type ConnectResponse struct {
	JobId    string
	Progress int64
	Error    string
}

func NewConnectResponseWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := &ConnectResponse{}
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

func DeserializeConnectResponse(r io.Reader) (*ConnectResponse, error) {
	t := NewConnectResponse()

	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	return t, err
}

func NewConnectResponse() *ConnectResponse {
	return &ConnectResponse{}
}

func (r *ConnectResponse) Schema() string {
	return "{\"fields\":[{\"name\":\"JobId\",\"type\":\"string\"},{\"name\":\"Progress\",\"type\":\"long\"},{\"name\":\"Error\",\"type\":\"string\"}],\"name\":\"ConnectResponse\",\"namespace\":\"com.pharbers.kafka.schema\",\"type\":\"record\"}"
}

func (r *ConnectResponse) SchemaName() string {
	return "com.pharbers.kafka.schema.ConnectResponse"
}

func (r *ConnectResponse) Serialize(w io.Writer) error {
	return writeConnectResponse(r, w)
}

func (_ *ConnectResponse) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ *ConnectResponse) SetInt(v int32)       { panic("Unsupported operation") }
func (_ *ConnectResponse) SetLong(v int64)      { panic("Unsupported operation") }
func (_ *ConnectResponse) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ *ConnectResponse) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ *ConnectResponse) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ *ConnectResponse) SetString(v string)   { panic("Unsupported operation") }
func (_ *ConnectResponse) SetUnionElem(v int64) { panic("Unsupported operation") }
func (r *ConnectResponse) Get(i int) types.Field {
	switch i {
	case 0:
		return (*types.String)(&r.JobId)
	case 1:
		return (*types.Long)(&r.Progress)
	case 2:
		return (*types.String)(&r.Error)

	}
	panic("Unknown field index")
}
func (r *ConnectResponse) SetDefault(i int) {
	switch i {

	}
	panic("Unknown field index")
}
func (_ *ConnectResponse) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *ConnectResponse) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *ConnectResponse) Finalize()                        {}

type ConnectResponseReader struct {
	r io.Reader
	p *vm.Program
}

func NewConnectResponseReader(r io.Reader) (*ConnectResponseReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewConnectResponse()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &ConnectResponseReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r *ConnectResponseReader) Read() (*ConnectResponse, error) {
	t := NewConnectResponse()
	err := vm.Eval(r.r, r.p, t)
	return t, err
}
