// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     ConnectRequest.avsc
 *     ConnectResponse.avsc
 *     MonitorRequest.avsc
 *     MonitorResponse.avsc
 *     TmAggRequest.avsc
 *     TmAggResponse.avsc
 */

package schema

import (
	"github.com/actgardner/gogen-avro/compiler"
	"github.com/actgardner/gogen-avro/container"
	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
	"io"
)

type ConnectRequest struct {
	JobId        string
	Tag          string
	SourceConfig string
	SinkConfig   string
}

func NewConnectRequestWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := &ConnectRequest{}
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

func DeserializeConnectRequest(r io.Reader) (*ConnectRequest, error) {
	t := NewConnectRequest()

	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	return t, err
}

func NewConnectRequest() *ConnectRequest {
	return &ConnectRequest{}
}

func (r *ConnectRequest) Schema() string {
	return "{\"fields\":[{\"name\":\"JobId\",\"type\":\"string\"},{\"name\":\"Tag\",\"type\":\"string\"},{\"name\":\"SourceConfig\",\"type\":\"string\"},{\"name\":\"SinkConfig\",\"type\":\"string\"}],\"name\":\"ConnectRequest\",\"namespace\":\"com.pharbers.kafka.schema\",\"type\":\"record\"}"
}

func (r *ConnectRequest) SchemaName() string {
	return "com.pharbers.kafka.schema.ConnectRequest"
}

func (r *ConnectRequest) Serialize(w io.Writer) error {
	return writeConnectRequest(r, w)
}

func (_ *ConnectRequest) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ *ConnectRequest) SetInt(v int32)       { panic("Unsupported operation") }
func (_ *ConnectRequest) SetLong(v int64)      { panic("Unsupported operation") }
func (_ *ConnectRequest) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ *ConnectRequest) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ *ConnectRequest) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ *ConnectRequest) SetString(v string)   { panic("Unsupported operation") }
func (_ *ConnectRequest) SetUnionElem(v int64) { panic("Unsupported operation") }
func (r *ConnectRequest) Get(i int) types.Field {
	switch i {
	case 0:
		return (*types.String)(&r.JobId)
	case 1:
		return (*types.String)(&r.Tag)
	case 2:
		return (*types.String)(&r.SourceConfig)
	case 3:
		return (*types.String)(&r.SinkConfig)

	}
	panic("Unknown field index")
}
func (r *ConnectRequest) SetDefault(i int) {
	switch i {

	}
	panic("Unknown field index")
}
func (_ *ConnectRequest) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *ConnectRequest) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *ConnectRequest) Finalize()                        {}

type ConnectRequestReader struct {
	r io.Reader
	p *vm.Program
}

func NewConnectRequestReader(r io.Reader) (*ConnectRequestReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewConnectRequest()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &ConnectRequestReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r *ConnectRequestReader) Read() (*ConnectRequest, error) {
	t := NewConnectRequest()
	err := vm.Eval(r.r, r.p, t)
	return t, err
}
