// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     ConnectRequest.avsc
 *     ConnectResponse.avsc
 *     MonitorRequest.avsc
 *     MonitorResponse.avsc
 *     TmAggRequest.avsc
 *     TmAggResponse.avsc
 */

package schema

import (
	"github.com/actgardner/gogen-avro/compiler"
	"github.com/actgardner/gogen-avro/container"
	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
	"io"
)

type MonitorRequest2 struct {
	JobId         string
	ConnectorName string
	SourceTopic   string
	RecallTopic   string
	Strategy      string
}

func NewMonitorRequest2Writer(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := &MonitorRequest2{}
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

func DeserializeMonitorRequest2(r io.Reader) (*MonitorRequest2, error) {
	t := NewMonitorRequest2()

	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	return t, err
}

func NewMonitorRequest2() *MonitorRequest2 {
	return &MonitorRequest2{}
}

func (r *MonitorRequest2) Schema() string {
	return "{\"fields\":[{\"name\":\"jobId\",\"type\":\"string\"},{\"name\":\"connectorName\",\"type\":\"string\"},{\"name\":\"sourceTopic\",\"type\":\"string\"},{\"name\":\"recallTopic\",\"type\":\"string\"},{\"name\":\"strategy\",\"type\":\"string\"}],\"name\":\"MonitorRequest2\",\"namespace\":\"com.pharbers.kafka.monitor.schema\",\"type\":\"record\"}"
}

func (r *MonitorRequest2) SchemaName() string {
	return "com.pharbers.kafka.monitor.schema.MonitorRequest2"
}

func (r *MonitorRequest2) Serialize(w io.Writer) error {
	return writeMonitorRequest2(r, w)
}

func (_ *MonitorRequest2) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ *MonitorRequest2) SetInt(v int32)       { panic("Unsupported operation") }
func (_ *MonitorRequest2) SetLong(v int64)      { panic("Unsupported operation") }
func (_ *MonitorRequest2) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ *MonitorRequest2) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ *MonitorRequest2) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ *MonitorRequest2) SetString(v string)   { panic("Unsupported operation") }
func (_ *MonitorRequest2) SetUnionElem(v int64) { panic("Unsupported operation") }
func (r *MonitorRequest2) Get(i int) types.Field {
	switch i {
	case 0:
		return (*types.String)(&r.JobId)
	case 1:
		return (*types.String)(&r.ConnectorName)
	case 2:
		return (*types.String)(&r.SourceTopic)
	case 3:
		return (*types.String)(&r.RecallTopic)
	case 4:
		return (*types.String)(&r.Strategy)

	}
	panic("Unknown field index")
}
func (r *MonitorRequest2) SetDefault(i int) {
	switch i {

	}
	panic("Unknown field index")
}
func (_ *MonitorRequest2) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *MonitorRequest2) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *MonitorRequest2) Finalize()                        {}

type MonitorRequest2Reader struct {
	r io.Reader
	p *vm.Program
}

func NewMonitorRequest2Reader(r io.Reader) (*MonitorRequest2Reader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewMonitorRequest2()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &MonitorRequest2Reader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r *MonitorRequest2Reader) Read() (*MonitorRequest2, error) {
	t := NewMonitorRequest2()
	err := vm.Eval(r.r, r.p, t)
	return t, err
}
