// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     ConnectRequest.avsc
 *     ConnectResponse.avsc
 *     MonitorRequest.avsc
 *     MonitorResponse.avsc
 *     TmAggRequest.avsc
 *     TmAggResponse.avsc
 */

package schema

import (
	"github.com/actgardner/gogen-avro/compiler"
	"github.com/actgardner/gogen-avro/container"
	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
	"io"
)

type TmAggResponse struct {
	RequestId string
	JobId     string
	Status    string
	Message   string
}

func NewTmAggResponseWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := &TmAggResponse{}
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

func DeserializeTmAggResponse(r io.Reader) (*TmAggResponse, error) {
	t := NewTmAggResponse()

	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	return t, err
}

func NewTmAggResponse() *TmAggResponse {
	return &TmAggResponse{}
}

func (r *TmAggResponse) Schema() string {
	return "{\"fields\":[{\"name\":\"RequestId\",\"type\":\"string\"},{\"name\":\"JobId\",\"type\":\"string\"},{\"name\":\"Status\",\"type\":\"string\"},{\"name\":\"Message\",\"type\":\"string\"}],\"name\":\"TmAggResponse\",\"namespace\":\"com.pharbers.kafka.schema\",\"type\":\"record\"}"
}

func (r *TmAggResponse) SchemaName() string {
	return "com.pharbers.kafka.schema.TmAggResponse"
}

func (r *TmAggResponse) Serialize(w io.Writer) error {
	return writeTmAggResponse(r, w)
}

func (_ *TmAggResponse) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ *TmAggResponse) SetInt(v int32)       { panic("Unsupported operation") }
func (_ *TmAggResponse) SetLong(v int64)      { panic("Unsupported operation") }
func (_ *TmAggResponse) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ *TmAggResponse) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ *TmAggResponse) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ *TmAggResponse) SetString(v string)   { panic("Unsupported operation") }
func (_ *TmAggResponse) SetUnionElem(v int64) { panic("Unsupported operation") }
func (r *TmAggResponse) Get(i int) types.Field {
	switch i {
	case 0:
		return (*types.String)(&r.RequestId)
	case 1:
		return (*types.String)(&r.JobId)
	case 2:
		return (*types.String)(&r.Status)
	case 3:
		return (*types.String)(&r.Message)

	}
	panic("Unknown field index")
}
func (r *TmAggResponse) SetDefault(i int) {
	switch i {

	}
	panic("Unknown field index")
}
func (_ *TmAggResponse) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *TmAggResponse) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *TmAggResponse) Finalize()                        {}

type TmAggResponseReader struct {
	r io.Reader
	p *vm.Program
}

func NewTmAggResponseReader(r io.Reader) (*TmAggResponseReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewTmAggResponse()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &TmAggResponseReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r *TmAggResponseReader) Read() (*TmAggResponse, error) {
	t := NewTmAggResponse()
	err := vm.Eval(r.r, r.p, t)
	return t, err
}
